### ISSUE TITLE
Pkg.build error

### ISSUE THREAD

**Issue by OVGULIU** [cvdlab/LinearAlgebraicRepresentation.jl#66]
ERROR: The following package names could not be resolved:
 * LinearAlgebraicRepresentation.jl (not found in project or manifest)
Please specify by known `name=uuid`.

**Comment by furio** [comment]
Hi, we've just asked for inclusion of the julia 1.0 compatible package. Could be the issue there?

**Comment by furio** [comment]
This should be fixed now
